### ISSUE TITLE
[Migration]: Error while migrating the dotnet project to support VS 2017

### ISSUE THREAD

**Issue by SrivatsaMarichi** [dotnet/cli-migrate#48]
Hi Team,

When I ran "dotnet migrate MY_SOLUTION --skip-backup" I ended up with the following error.
![error1](https://user-images.githubusercontent.com/13433045/31546035-38f8808a-b011-11e7-8179-6a01098daa69.png)

URL for the Project: https://github.com/SrivatsaMarichi/dotnet_migrate/tree/master 

Dotnet Information-

![dotnet_info](https://user-images.githubusercontent.com/13433045/31546592-755eba56-b013-11e7-8c0a-b717376389ec.png)

@blackdwarf, @livarcocc

**Comment by livarcocc** [comment]
You need to remove the postrestore event as it is not supported, as the message indicates. Also, move the exclude around and then try to migrate again.

**Comment by SrivatsaMarichi** [comment]
Yep, it worked thanks!
